// Exports contract ABIs from Foundry artifacts into shared/src/abis as typed
// TypeScript modules. Run from shared/: npm run build:abis (after forge build).
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "../../contracts/out");
const abisDir = join(here, "../src/abis");

const CONTRACTS = ["DelegationMirror", "GatedUSD", "MockYieldVault", "ServiceSink"];

await mkdir(abisDir, { recursive: true });

const indexLines = [];
for (const name of CONTRACTS) {
  const artifactPath = join(outDir, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  const body = `// Generated by shared/scripts/build-abis.mjs, do not edit.\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  await writeFile(join(abisDir, `${name}.ts`), body);
  indexLines.push(`export { ${name}Abi } from "./${name}.js";`);
}
await writeFile(join(abisDir, "index.ts"), indexLines.join("\n") + "\n");

console.log(`Wrote ABIs for ${CONTRACTS.join(", ")} to shared/src/abis`);
